# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af1f31b914d986d600f55046d3d858e3f1791a67a19b89f51ac9c20da0b68f4a6afd2a876931500522b12545aea2f2cb5d4a2102ad725f0c3d8d30eb50aab1af

test:
  secret_key_base: 7deef02a4712dad87c55a0f0cdc6a437c9814a18840cead76f7690d58764e2bb3ef06b29fd54a8a537fafeeef532023d875e222906595bfe1959ac13cc016229

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
